baseurl = "https://example.org/"
languageCode = "en-us"
title = "Naturalis Biodiversity Api documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	 author = "Digitalcraftsman"
	# description = "A material design theme for documentations."
	# copyright = "Released under the MIT license"

	# Repository
	##provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0.0"
	logo = "images/logo.jpg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "digitalcraftsman"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Introduction"
	url    = "introduction/"
	weight = 10

[[menu.main]]
	name   = "Quick start"
	url    = "quickstart/"
	weight = 20

[[menu.main]]
	name   = "Advanced Queries"
	url    = "advanced-queries/"
	weight = 30

[[menu.main]]
	name   = "Document specific services"
	url    = "doc-spec-services/"
	weight = 40

[[menu.main]]
	name   = "Download services"
	url    = "download-services/"
	weight = 50

[[menu.main]]
	name   = "PURL services"
	url    = "purl-services/"
	weight = 60
	

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
