baseurl = "/"
languageCode = "en-us"
title = "Netherlands Biodiversity Data Services"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	release = "V2.16.1-docsV1-2018-10-18"
	nba_release = "V2.16.1"
	author = "Naturalis"
	support_email="nba@naturalis.nl"
	license="https://github.com/naturalis/naturalis_data_api/blob/V2_master/LICENSE"
	description = "Netherlans Biodiversity Data Services - User documentation"	
	copyright = "License: CC0"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/naturalis/naturalis_data_api"

	version = "v2"
	logo = "images/Naturalis_logo_notext.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"
	
[[menu.main]]
	name   = "Introduction"
	url    = "introduction/"
	weight = 10

[[menu.main]]
	name   = "Quick start"
	url    = "quickstart/"
	weight = 30

[[menu.main]]
	name   = "Specimen occurrence services"
	url    = "doc-spec-services/specimen/"
	weight = 30	

[[menu.main]]
	name   = "Taxonomic data services"
	url    = "doc-spec-services/taxon/"
	weight = 40	

[[menu.main]]
	name   = "Geographical data services"
	url    = "doc-spec-services/geo/"
	weight = 50

[[menu.main]]
	name   = "Multimedia data services"
	url    = "doc-spec-services/multimedia/"
	weight = 60

[[menu.main]]
	name   = "Metadata services"
	url    = "doc-spec-services/metadata/"
	weight = 70
						
[[menu.main]]
	name   = "Advanced queries"
	url    = "advanced-queries/"
	weight = 80

[[menu.purl]]
	name   = "PURL services"
	url    = "purl-services/"
	weight = 90
	
[[menu.misc]]
	name   = "Known issues"
	url    = "misc/issues/"
	weight = 100

	
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
