version: '3'
    
services:
    swagger-ui:
        image: naturalis/swagger-ui
        environment:
            - VALIDATOR_URL=null
            - API_URL=http://${NBA_HOST}:${NBA_PORT}/v2/reference-doc
            - NBA_PORT=${NBA_PORT}
        ports:
            - "$SWAGGER_UI_PORT:80"

    nba-docs:
        image: naturalis/nba-docs
        environment:
            - SWAGGER_UI_URL=http://145.136.242.164/swagger
            - SWAGGER_UI_URL=http://${SWAGGER_UI_HOST}:${SWAGGER_UI_PORT}/${SWAGGER_UI_PATH}
            - NBADOCS_HOST=$NBADOCS_HOST
            - NBADOCS_PORT=$NBADOCS_PORT
            - NBADOCS_PATH=$NBADOCS_PATH
            - NBA_BASE_URL=http://${NBA_HOST}:${NBA_PORT}
            - SCRATCHPAD_URL=http://${SCRATCHPAD_HOST}:${SCRATCHPAD_PORT}/${SCRATCHPAD_PATH}
        ports:
            - "$NBADOCS_PORT:$NBADOCS_PORT"
   
    nba_scratchpad:
        image: naturalis/nba_scratchpad:latest
        environment:
            - NBA_ADDRESS=$NBA_HOST
            - NBA_PORT=$NBA_PORT
            - NBA_TIMEOUT=15
            - PUBLIC_NBA_FULL_ADDRESS=${NBA_HOST}:${NBA_PORT}
        ports:
            - "$SCRATCHPAD_PORT:80"
